### ISSUE TITLE
Repository is missing some files and relies on other repositories.

### ISSUE THREAD

**Issue by msarson** [Dennis-Evans/FileManager_ODBC#18]
Currently the repository seems to be missing the fileMgrOdbc.* files and the odbc*.* files needed to be able to compile the project.

I appreciate you have separated the odbc*.* files into a separate directory, but feel it might be worth documenting this in the readme.md

Personally, I wonder, as one needs the other if both repositories need to be merged together so that the less git friendly clarion developer doesn't start to get overwhelmed? 

Also, although I can guess for the most part, I wonder if it would be an idea to have a directory structure.

Libsrc\win\ for all files needed to get this to work within a clarion app.
Demo\ for the demo files.

Obviously anyone cloning or forking the repository should have enough knowledge to know where to put all this IMHO, but obviously as this is work you have done off your own back, I do also appreciate you are not here to hold hands.

**Comment by Dennis-Evans** [comment]
added the missing files and moved the ODBC and the demo/test files to a sub-directory
should make it simpler just clone and go
